version: "3.7"
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - APP_DB_USER=postgres
      - APP_DB_PASS=password
      - APP_DB_NAME=myproject
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: always
    networks:
      - app-network

  apidjango:
    build: ./api/
    container_name: ApiDjango
    ports:
      - 8080:8080
    command: sh -c "python ../api/manage.py migrate && python manage.py test && python ../api/manage.py runserver"
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

  clientnode:
    build: ./client/
    container_name: ClientNode
    command: sh -c "npm install -g @quasar/cli  && quasar dev"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - apidjango
    networks:
      - app-network

volumes:
  postgres:
networks:
  app-network:
    driver: bridge
